name: Build Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sparkfabrik/android-build-action@v1.2.0
      with:
        project-path: .
        output-path: my-app.apk
