name: Build Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "gradle assembleDebug"

