name: Build Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build
    - uses: sparkfabrik/android-build-action@v1.0.0
      with:
        project-path: .
