name: Build Android App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: automated-build-android-app-with-github-action
      uses: amirisback/automated-build-android-app-with-github-action@2.1.0

